# Cross Validation of Model Scores 

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

digits  = load_digits()

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=.2)

lr = LogisticRegression()
lr.fit(X_train, y_train)


In [20]:
lr = LogisticRegression(solver='liblinear')
lr.fit(X_test, y_test)
lr.score(X_test,y_test)

1.0

In [21]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9805555555555555

In [22]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9638888888888889

In [23]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [24]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [25]:
def get_score (model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [26]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10)

In [27]:

scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='liblinear'),X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test))

In [28]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [29]:
scores_svm 

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [30]:
scores_rf

[0.9215358931552587, 0.9465776293823038, 0.9115191986644408]

In [31]:
from sklearn.model_selection import cross_val_score

In [32]:
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [33]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.93611111, 0.91388889, 0.9637883 , 0.96935933, 0.91643454])